version: "3.7"
services:
  mongo-filmes:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=homeflix_pw
      - MONGO_INITDB_ROOT_DATABASE=root-db
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    container_name: homeflix_filmes_db
    ports:
      - 30002:27017
    networks:
      - HomeFlix

  #homeflix_filmes:
   # build: ./HomeFlix-Filmes
    #depends_on:
     # - mongo-filmes
    
    #networks:
     # - HomeFlix
    #ports:
      #- 3000:3000

networks:
  HomeFlix:
    driver: bridge